# Generated by Django 5.1 on 2024-08-29 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_period_album_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
