# Generated by Django 5.1 on 2024-09-17 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0007_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='rym_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
