# Generated by Django 5.1 on 2024-09-18 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0009_rename_year_album_release_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='rym_rating',
        ),
    ]
